
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: DRF_AUTH_DB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: ./DRFAuth  
    volumes:
      - ./DRFAuth:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: